# Generated by Django 2.2.5 on 2022-04-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='conversations.Conversation'),
            preserve_default=False,
        ),
    ]
